version: "3.8"
services:
  rediska:
    image: redis:7.0.0
    hostname: rediska
    container_name: re-chinese-redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    env_file:
      - .env
    expose:
      - 6379
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    restart: always
    volumes:
      - redis-data:/data
  api:
    # image: ${IMAGE_BACKEND}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: re-chinese-backend
    env_file:
      - .env
    environment:
      - REDIS_ADDR=rediska:6379
      - GIN_MODE=release
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - rediska
    links:
      - rediska
    restart: always
volumes:
  redis-data:
    driver: local
