version: "3.8"
services:
  redis:
    image: redis
    hostname: redis
    container_name: re-chinese-redis
    environment:
      - REDIS_PASREDIS_ADDRSWORD=${REDIS_PASSWORD}
    env_file:
      - .env
    expose:
      - 6379
    ports:
      - 6379:6379
    networks:
      - default
    restart: always
  api:
    # image: ${IMAGE_BACKEND}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: re-chinese-backend
    env_file:
      - .env
    expose:
      - 8080
    ports:
      - 8080:8080
    networks:
      - default
    depends_on:
      - redis
    restart: always
